<?php

return [
    'pages' => [
        'users' => ['Manajemen Pengguna', 'Kelola akun admin dan super admin.', ['Nama', 'Email', 'Role', 'Status', 'Login Terakhir'], [['Owner Farm', 'owner@example.com', 'Super Admin', 'Aktif', '-']]],
        'animals' => ['Data Kambing', 'Kelola identitas umum, eartag, foto, ras, asal ternak, dan status ternak.', ['Eartag', 'Ras Kambing', 'Generasi', 'Jenis Kelamin', 'Asal Ternak', 'Status Ternak', 'Umur'], [['26-001-SPB', 'Boer', 'F1', 'Jantan', 'Lahir Internal', 'Aktif', '2 tahun']]],
        'weight-records' => ['Catatan Bobot', 'Pantau riwayat bobot ternak.', ['Tag Kambing', 'Tanggal Timbang', 'Berat (Kg)', 'Umur', 'Catatan'], [['BBH-001', '30/05/2026', '42', '2 Tahun', '-'], ['BBH-014', '29/05/2026', '36.5', '1 Tahun 4 Bulan', 'Kondisi stabil']]],
        'pens' => ['Kandang & Koloni', 'Kelola kandang, koloni, fase, dan kapasitas.', ['Kode Kandang', 'Kode Koloni', 'Nama Koloni', 'Fase Koloni', 'Lokasi Kandang', 'Kapasitas', 'Status'], [['KDG-01', 'A1', 'Koloni Kawin A1', 'Kawin', 'Blok Utara 1', '12', 'Aktif']]],
        'pen-movements' => ['Pindah Koloni', 'Catat riwayat perpindahan kambing antar koloni.', ['Eartag', 'Dari Koloni', 'Ke Koloni', 'Tanggal Keluar/Masuk Koloni', 'Alasan'], [['26-001-SPB', 'KDG-01', 'KDG-02', '01/07/2026', 'Masuk bunting']]],
        'breeding-periods' => ['Periode Kawin', 'Kelola periode perkawinan dan koloni kawin.', ['Kode Periode Kawin', 'Kode Kandang', 'Tanggal Mulai', 'Tanggal Selesai', 'Tag Pejantan', 'Status'], [['PK-001', 'KDG-01', '01/05/2026', '30/05/2026', '24-001-SPB', 'Aktif']]],
        'breeding-females' => ['Betina Kawin', 'Daftar betina dalam periode kawin.', ['Kode Periode Kawin', 'Eartag Betina', 'Tanggal Masuk', 'Tanggal Kawin', 'Perkiraan Lahir', 'Tahap Siklus', 'Tanggal Keluar', 'Alasan Keluar'], [['PK-001', '26-014-SPB', '03/05/2026', '03/05/2026', '13/10/2026', 'Kawin', '-', '-']]],
        'pregnancy-checks' => ['Kebuntingan', 'Catatan pemeriksaan kebuntingan.', ['Kode Periode', 'Kode Kandang', 'Pejantan', 'Tanggal Mulai', 'Tanggal Selesai', 'Status Periode'], [['PK-001', 'KDG-01', 'BBH-001', '01/05/2026', '30/05/2026', 'Aktif']]],
        'birth-events' => ['Kelahiran', 'Catatan peristiwa kelahiran.', ['Tag Pejantan', 'Tag Betina', 'Tanggal Lahir', 'Jam Lahir', 'Jumlah Anak', 'Proses Kelahiran', 'Tempat Kelahiran'], [['SPB-26-001', 'BBH-26-014', '30/05/2026', '06:15', '2', 'Normal', 'Blok Kelahiran']]],
        'offspring-births' => ['Cempe Lahir', 'Data anak kambing hasil kelahiran.', ['Tanggal Kelahiran', 'Eartag Anak', 'Berat Lahir (Kg)', 'Grade Anak', 'Status Anak', 'Catatan'], [['30/05/2026', 'BBH-26-015', '3.2', 'A', 'Hidup', '-']]],
        'health-treatments' => ['Kesehatan', 'Track record kesehatan individu kambing.', ['Eartag', 'Tanggal Perawatan', 'Jenis Perawatan', 'Gejala', 'Diagnosis', 'Nama Obat', 'Dosis', 'Kontrol Berikutnya'], [['26-001-SPB', '28/05/2026', 'Pemeriksaan Rutin', 'Nafsu makan turun', 'Observasi', 'Vitamin B', '10 ml', '02/06/2026']]],
        'vaccinations' => ['Vaksinasi', 'Catatan vaksinasi ternak.', ['Tag Kambing', 'Jenis Vaksin', 'Tanggal Vaksin', 'Nama Vaksin', 'Dosis', 'Cara Pemberian'], [['BBH-001', 'Vaksin A', '20/05/2026', 'Vaksin Enterotoxemia', '2 ml', 'Subkutan (SC)']]],
        'postnatal-care' => ['Pascalahir', 'Catatan perawatan setelah kelahiran.', ['Data Kelahiran', 'Tag Cempe', 'Tanggal Perawatan', 'Metode Kolostrum', 'Volume Kolostrum', 'Iodin Pusar', 'Vitamin ADE', 'B-Complex', 'Intracin'], [['Kelahiran BBH-014', 'CMP-001', '30/05/2026', 'DOT', '250 ml', 'Ok', '1 ml', '1 ml', '0.5 ml']]],
        'certificates' => ['Akte & Sertifikat', 'Kelola dokumen sertifikat ternak.', ['Nomor Sertifikat', 'Tag Kambing', 'Jenis Sertifikat', 'Tanggal Terbit', 'Status'], [['CERT-001', 'BBH-001', 'Sertifikat Bibit Unggul', '30/05/2026', 'Aktif'], ['CERT-002', 'BBH-014', 'Akte Kematian', '29/05/2026', 'Dicabut']]],
        'certificate-logs' => ['Log Sertifikat', 'Riwayat verifikasi sertifikat.', ['Nomor Sertifikat', 'Tanggal', 'Waktu', 'Metode', 'Hasil', 'Catatan Alasan', 'IP Address'], [['CERT-001', '30/05/2026', '10:00', 'QR Code', 'Valid', '-', '127.0.0.1'], ['CERT-002', '30/05/2026', '10:12', 'Nomor Sertifikat', 'Tidak Valid', 'Tanda tangan digital tidak cocok', '127.0.0.1']]],
        'activity-logs' => ['Log Aktivitas', 'Riwayat aktivitas admin.', ['Tanggal', 'Waktu', 'Pengguna', 'Modul', 'Aksi', 'Detail', 'Hasil', 'IP Address'], [['30/05/2026', '10:00', 'Owner Farm', 'Data Kambing', 'Tambah Data', 'Objek: BBH-001', 'Berhasil', '127.0.0.1'], ['30/05/2026', '10:20', 'Owner Farm', 'Sertifikat', 'Tanda Tangan Sertifikat', 'Objek: CERT-001', 'Berhasil', '127.0.0.1']]],
        'rsa-keys' => ['RSA Key', 'Kelola rotasi RSA key sertifikat.', ['Key Identifier', 'Algoritma', 'Panjang', 'Fingerprint', 'Status'], [['BBH-RSA-POSTMAN', 'RSA', '2048', '1B:33:9C:37...DE:CC', 'Aktif'], ['RSA-DEMO-20260517105904', 'RSA', '2048', 'A1:02:14:6D...AF:A1', 'Retired']]],
    ],

    'forms' => [
        'users' => [
            ['name' => 'first_name', 'label' => 'Nama Depan', 'type' => 'text', 'placeholder' => 'Nama depan', 'required' => true],
            ['name' => 'last_name', 'label' => 'Nama Belakang', 'type' => 'text', 'placeholder' => 'Nama belakang'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'email@farm.com', 'required' => true],
            ['name' => 'password', 'label' => 'Password', 'type' => 'password', 'placeholder' => 'Minimal 8 karakter', 'required_on_create' => true],
            ['name' => 'password_confirmation', 'label' => 'Konfirmasi Password', 'type' => 'password', 'placeholder' => 'Ulangi password', 'required_on_create' => true],
            ['name' => 'role', 'label' => 'Role', 'type' => 'select', 'placeholder' => 'Pilih role', 'options' => ['super_admin' => 'Super Admin', 'admin' => 'Admin'], 'required' => true],
            ['name' => 'is_active', 'label' => 'Status Aktif', 'type' => 'radio', 'options' => ['true' => 'Aktif', 'false' => 'Nonaktif'], 'hide_on_create' => true],
        ],
        'animals' => [
            ['name' => 'photo', 'label' => 'Foto Kambing', 'type' => 'file', 'accept' => 'image/*'],
            ['name' => 'tag_number', 'label' => 'Nomor Eartag', 'type' => 'text', 'placeholder' => 'Kosongkan untuk otomatis, contoh: 26-001-SPB'],
            ['name' => 'breed_id', 'label' => 'Ras Kambing', 'type' => 'select', 'placeholder' => 'Pilih ras kambing', 'options' => ['Boer', 'Saanen', 'Etawa'], 'required' => true],
            ['name' => 'generation', 'label' => 'Generasi', 'type' => 'select', 'placeholder' => 'Pilih generasi', 'options' => ['F1', 'F2', 'F3', 'F4', 'F5', 'Pure Breed'], 'required' => true],
            ['name' => 'birth_date', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true],
            ['name' => 'birth_place', 'label' => 'Tempat Lahir', 'type' => 'text', 'placeholder' => 'Masukan lokasi kelahiran'],
            ['name' => 'life_status', 'label' => 'Status Hidup', 'type' => 'select', 'options' => ['alive' => 'Hidup', 'dead' => 'Mati']],
            ['name' => 'sex', 'label' => 'Jenis Kelamin', 'type' => 'radio', 'options' => ['male' => 'Jantan', 'female' => 'Betina']],
            ['name' => 'origin_type', 'label' => 'Asal Ternak', 'type' => 'select', 'placeholder' => 'Pilih asal ternak', 'options' => ['internal_birth' => 'Lahir Internal', 'purchase' => 'Pembelian', 'import' => 'Impor', 'grant' => 'Hibah', 'unknown' => 'Tidak Diketahui']],
            ['name' => 'origin_detail', 'label' => 'Detail Asal', 'type' => 'text', 'placeholder' => 'Contoh: nama peternakan asal / pemasok'],
            ['name' => 'exit_status', 'label' => 'Status Ternak', 'type' => 'select', 'placeholder' => 'Pilih status khusus jika ada', 'options' => ['sold' => 'Dijual', 'culled' => 'Afkir / Tidak Produktif', 'lost' => 'Hilang'], 'hide_on_create' => true],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan identitas (misal: ciri khusus, warna bulu, dll)...', 'span' => 2],
        ],
        'weight-records' => [
            ['name' => 'animal_id', 'label' => 'Tag Kambing', 'type' => 'select', 'placeholder' => 'Pilih Tag Kambing', 'options' => ['BBH-001', 'BBH-014'], 'required' => true],
            ['name' => 'record_date', 'label' => 'Tanggal Timbang', 'type' => 'date', 'required' => true],
            ['name' => 'weight_kg', 'label' => 'Berat (Kg)', 'type' => 'number', 'placeholder' => 'Contoh: 56.5', 'step' => '0.1', 'required' => true],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan penimbangan', 'span' => 2],
        ],
        'pens' => [
            ['name' => 'pen_code', 'label' => 'Kode Kandang', 'type' => 'text', 'placeholder' => 'Contoh KDN-A1-01', 'required' => true],
            ['name' => 'colony_code', 'label' => 'Kode Koloni', 'type' => 'text', 'placeholder' => 'Contoh: A1'],
            ['name' => 'colony_name', 'label' => 'Nama Koloni', 'type' => 'text', 'placeholder' => 'Contoh: Koloni Kawin A1'],
            ['name' => 'colony_phase', 'label' => 'Fase Koloni', 'type' => 'select', 'placeholder' => 'Pilih fase koloni', 'options' => ['koloni_kawin' => 'Kawin', 'koloni_bunting' => 'Bunting', 'koloni_kering' => 'Kering', 'koloni_laktasi' => 'Laktasi', 'koloni_anak' => 'Anak'], 'required' => true],
            ['name' => 'location', 'label' => 'Lokasi Kandang', 'type' => 'text', 'placeholder' => 'Contoh: Blok Utara 1', 'required' => true],
            ['name' => 'capacity', 'label' => 'Kapasitas', 'type' => 'number', 'placeholder' => '0', 'required' => true],
            ['name' => 'is_active', 'label' => 'Status Aktif', 'type' => 'radio', 'options' => ['true' => 'Aktif', 'false' => 'Nonaktif'], 'hide_on_create' => true],
        ],
        'pen-movements' => [
            ['name' => 'animal_id', 'label' => 'Eartag Kambing', 'type' => 'select', 'placeholder' => 'Pilih kambing', 'options' => ['26-001-SPB'], 'required' => true],
            ['name' => 'from_pen_preview', 'label' => 'Koloni Saat Ini', 'type' => 'display', 'placeholder' => 'Otomatis mengikuti eartag', 'span' => 2],
            ['name' => 'to_pen_id', 'label' => 'Koloni Tujuan', 'type' => 'select', 'placeholder' => 'Pilih koloni tujuan', 'options' => ['KDG-01', 'KDG-02'], 'required' => true],
            ['name' => 'movement_date', 'label' => 'Tanggal Keluar/Masuk Koloni', 'type' => 'date', 'required' => true],
            ['name' => 'reason', 'label' => 'Alasan Keluar/Pindah', 'type' => 'text', 'placeholder' => 'Contoh: Masuk bunting'],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan perpindahan', 'span' => 2],
        ],
        'breeding-periods' => [
            ['name' => 'period_code', 'label' => 'Kode Periode', 'type' => 'text', 'placeholder' => 'Contoh: PRD-2024-001', 'required' => true],
            ['name' => 'colony_pen_id', 'label' => 'Kode Kandang', 'type' => 'select', 'placeholder' => 'Pilih Kode Kandang', 'options' => ['KDG-01', 'KDG-02'], 'required' => true],
            ['name' => 'start_date', 'label' => 'Tanggal Mulai', 'type' => 'date', 'required' => true],
            ['name' => 'end_date', 'label' => 'Tanggal Selesai', 'type' => 'date'],
            ['name' => 'male_animal_id', 'label' => 'Tag Pejantan', 'type' => 'select', 'placeholder' => 'Pilih Tag Pejantan', 'options' => ['BBH-001', 'BBH-022'], 'required' => true],
            ['name' => 'status', 'label' => 'Status Periode', 'type' => 'select', 'options' => ['active' => 'Aktif', 'closed' => 'Ditutup'], 'required' => true, 'hide_on_create' => true],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan khusus...', 'span' => 2],
        ],
        'breeding-females' => [
            ['name' => 'breeding_period_id', 'label' => 'Kode Periode', 'type' => 'select', 'placeholder' => 'Pilih Kode Periode', 'options' => ['PK-001', 'PK-002'], 'required' => true, 'hide_on_edit' => true],
            ['name' => 'breeding_period.period_code', 'label' => 'Kode Periode', 'type' => 'display', 'placeholder' => '-', 'show_on_edit' => true],
            ['name' => 'female_animal.tag_number', 'label' => 'Tag Betina', 'type' => 'display', 'placeholder' => '-', 'show_on_edit' => true],
            ['name' => 'female_animal_ids', 'label' => 'Tag Betina', 'type' => 'multiselect', 'placeholder' => 'Pilih satu atau beberapa betina', 'options' => ['BBH-014', 'BBH-020'], 'required' => true, 'hide_on_edit' => true],
            ['name' => 'entry_date', 'label' => 'Tanggal Masuk', 'type' => 'date', 'required' => true],
            ['name' => 'mating_date', 'label' => 'Tanggal Kawin', 'type' => 'display', 'placeholder' => 'Belum dicatat', 'show_on_edit' => true],
            ['name' => 'expected_birth_preview', 'label' => 'Perkiraan Lahir', 'type' => 'display', 'placeholder' => 'Otomatis setelah tanggal kawin diisi', 'display_role' => 'birth-estimate', 'show_on_edit' => true],
            ['name' => 'cycle_stage', 'label' => 'Tahap Siklus', 'type' => 'select', 'options' => ['kawin' => 'Kawin', 'bunting' => 'Bunting', 'kering' => 'Kering', 'laktasi_kosong' => 'Laktasi Kosong', 'melahirkan' => 'Melahirkan']],
        ],
        'pregnancy-checks' => [
            ['name' => 'check_date', 'label' => 'Tanggal Periksa', 'type' => 'date', 'required' => true],
            ['name' => 'breeding_period_id', 'label' => 'Kode Periode', 'type' => 'select', 'placeholder' => 'Pilih Kode Periode', 'options' => ['PK-001', 'PK-002'], 'required' => true],
            ['name' => 'female_animal_id', 'label' => 'Tag Betina', 'type' => 'select', 'placeholder' => 'Pilih Tag Betina', 'options' => ['BBH-014', 'BBH-020'], 'required' => true],
            ['name' => 'is_pregnant', 'label' => 'Status Bunting', 'type' => 'select', 'placeholder' => 'Pilih Status', 'options' => ['1' => 'Bunting', '0' => 'Tidak Bunting'], 'required' => true],
            ['name' => 'method', 'label' => 'Metode Periksa', 'type' => 'select', 'placeholder' => 'Pilih Metode', 'options' => ['Palpasi', 'USG', 'Visual', 'Lainnya'], 'required' => true],
            ['name' => 'estimated_gestation_days', 'label' => 'Estimasi Usia', 'type' => 'number', 'placeholder' => '45'],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan pemeriksaan', 'span' => 2],
        ],
        'birth-events' => [
            ['name' => 'dam_id', 'label' => 'Tag Betina', 'type' => 'select', 'placeholder' => 'Pilih Tag Betina', 'options' => ['BBH-014', 'BBH-020'], 'required' => true],
            ['name' => 'sire_id', 'label' => 'Tag Pejantan', 'type' => 'select', 'placeholder' => 'Pejantan otomatis dari periode kawin', 'options' => ['BBH-001', 'BBH-022']],
            ['name' => 'birth_date', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true],
            ['name' => 'birth_time', 'label' => 'Jam Lahir', 'type' => 'time'],
            ['name' => 'offspring_count', 'label' => 'Jumlah Anak', 'type' => 'number', 'placeholder' => 'Masukkan jumlah anak', 'required' => true],
            ['name' => 'birth_process', 'label' => 'Proses Kelahiran', 'type' => 'select', 'placeholder' => 'Pilih Proses Kelahiran', 'options' => ['Normal', 'Bantuan', 'Caesar'], 'required' => true],
            ['name' => 'birth_place', 'label' => 'Tempat Kelahiran', 'type' => 'text', 'placeholder' => 'Masukkan tempat kelahiran', 'required' => true],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan', 'span' => 2],
        ],
        'offspring-births' => [
            ['name' => 'birth_event_id', 'label' => 'Data Kelahiran', 'type' => 'select', 'placeholder' => 'Pilih Data Kelahiran', 'options' => ['Kelahiran BBH-014 - 2026-05-30'], 'required' => true],
            ['name' => 'tag_number', 'label' => 'Tag Cempe', 'type' => 'text', 'placeholder' => 'Masukan tag kambing', 'hide_on_edit' => true],
            ['name' => 'breed_id', 'label' => 'Ras Cempe', 'type' => 'select', 'placeholder' => 'Pilih ras cempe', 'options' => ['Boer', 'Saanen', 'Etawa'], 'required' => true, 'hide_on_edit' => true],
            ['name' => 'generation', 'label' => 'Generasi', 'type' => 'select', 'placeholder' => 'Pilih generasi', 'options' => ['F1', 'F2', 'F3', 'F4', 'F5', 'Pure Breed'], 'required' => true, 'hide_on_edit' => true],
            ['name' => 'sex', 'label' => 'Jenis Kelamin', 'type' => 'radio', 'options' => ['male' => 'Jantan', 'female' => 'Betina'], 'hide_on_edit' => true],
            ['name' => 'birth_weight_kg', 'label' => 'Berat Lahir (Kg)', 'type' => 'number', 'placeholder' => 'Masukkan berat lahir', 'step' => '0.01', 'required' => true],
            ['name' => 'offspring_grade', 'label' => 'Grade Anak', 'type' => 'select', 'placeholder' => 'Pilih grade anak', 'options' => ['A' => 'A', 'B' => 'B', 'C' => 'C', 'D' => 'D']],
            ['name' => 'birth_status', 'label' => 'Status Hidup', 'type' => 'select', 'placeholder' => 'Pilih Status Hidup', 'options' => ['alive' => 'Hidup', 'dead' => 'Mati'], 'required' => true],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan', 'span' => 2],
        ],
        'health-treatments' => [
            ['name' => 'animal_id', 'label' => 'Tag Kambing', 'type' => 'select', 'placeholder' => 'Pilih Tag Kambing', 'options' => ['BBH-001', 'BBH-014'], 'required' => true],
            ['name' => 'treatment_date', 'label' => 'Tanggal Perawatan', 'type' => 'date', 'required' => true],
            ['name' => 'treatment_group', 'label' => 'Jenis Perawatan', 'type' => 'datalist', 'placeholder' => 'Contoh: Antibiotik', 'options' => ['Antibiotik', 'Antiparasit / Obat Cacing', 'Vitamin / Suplemen', 'Perawatan Luka', 'Pemeriksaan Rutin'], 'required' => true],
            ['name' => 'symptoms', 'label' => 'Gejala', 'type' => 'textarea', 'placeholder' => 'Catat gejala yang terlihat'],
            ['name' => 'diagnosis', 'label' => 'Diagnosis', 'type' => 'textarea', 'placeholder' => 'Catat hasil diagnosis/pemeriksaan'],
            ['name' => 'product_name', 'label' => 'Nama Obat / Produk', 'type' => 'text', 'placeholder' => 'Contoh: Enrofloxacin', 'required' => true],
            ['name' => 'dosage', 'label' => 'Dosis', 'type' => 'text', 'placeholder' => 'Contoh: 10 ml / 2 tablet'],
            ['name' => 'administration_route', 'label' => 'Cara Pemberian / Rute', 'type' => 'datalist', 'placeholder' => 'Contoh: Oral', 'options' => ['Oral', 'Subkutan (SC)', 'Intramuskular (IM)', 'Topikal', 'Intranasal']],
            ['name' => 'action_category', 'label' => 'Kategori Tindakan', 'type' => 'datalist', 'placeholder' => 'Contoh: Kuratif', 'options' => ['Preventif', 'Kuratif', 'Suportif', 'Rehabilitatif', 'Observasi'], 'span' => 2],
            ['name' => 'handled_by', 'label' => 'Ditangani Oleh', 'type' => 'text', 'placeholder' => 'Nama petugas/dokter'],
            ['name' => 'next_control_date', 'label' => 'Tanggal Kontrol Berikutnya', 'type' => 'date'],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan pemeriksaan, gejala, atau respons terapi', 'span' => 2],
        ],
        'vaccinations' => [
            ['name' => 'animal_id', 'label' => 'Tag Kambing', 'type' => 'select', 'placeholder' => 'Pilih Tag Kambing', 'options' => ['BBH-001', 'BBH-014'], 'required' => true],
            ['name' => 'category_name', 'label' => 'Jenis Vaksin', 'type' => 'datalist', 'placeholder' => 'Contoh: PMK', 'options' => ['PMK', 'Clostridial / Enterotoxemia', 'Tetanus', 'Anthrax', 'PPR', 'Orf / Ecthyma', 'Pasteurellosis / Pneumonia', 'Rabies'], 'required' => true],
            ['name' => 'vaccination_date', 'label' => 'Tanggal Vaksin', 'type' => 'date', 'required' => true],
            ['name' => 'product_name', 'label' => 'Nama Vaksin', 'type' => 'text', 'placeholder' => 'Masukkan nama vaksin', 'required' => true],
            ['name' => 'dosage', 'label' => 'Dosis (ml)', 'type' => 'number', 'placeholder' => 'Contoh: 2', 'step' => '0.1'],
            ['name' => 'administration_route', 'label' => 'Cara Pemberian / Rute', 'type' => 'datalist', 'placeholder' => 'Contoh: Subkutan (SC)', 'options' => ['Oral', 'Subkutan (SC)', 'Intramuskular (IM)', 'Topikal', 'Intranasal']],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan', 'span' => 2],
        ],
        'postnatal-care' => [
            ['name' => 'birth_event_id', 'label' => 'Data Kelahiran', 'type' => 'select', 'placeholder' => 'Pilih Data Kelahiran', 'options' => ['Kelahiran BBH-014 - 2026-05-30'], 'required' => true],
            ['name' => 'target_animal_id', 'label' => 'Tag Cempe Lahir', 'type' => 'select', 'placeholder' => 'Pilih Tag Cempe dari Data Kelahiran', 'options' => ['CMP-001', 'CMP-002'], 'required' => true],
            ['name' => 'administration_method', 'label' => 'Metode Pemberian Kolostrum', 'type' => 'text', 'placeholder' => 'Contoh: DOT', 'required' => true],
            ['name' => 'volume_ml', 'label' => 'Volume Kolostrum (ml)', 'type' => 'number', 'placeholder' => 'Contoh: 250', 'step' => '0.1', 'required' => true],
            ['name' => 'navel_iodine_status', 'label' => 'Pemberian Iodin Pusar', 'type' => 'text', 'placeholder' => 'Contoh: Ok'],
            ['name' => 'vitamin_ade_ml', 'label' => 'Suntik Vitamin ADE (ml)', 'type' => 'number', 'placeholder' => 'Masukkan volume vitamin ADE', 'step' => '0.1'],
            ['name' => 'vitamin_b_complex_ml', 'label' => 'Vitamin B-Complex (ml)', 'type' => 'number', 'placeholder' => 'Masukkan volume vitamin B-Complex', 'step' => '0.1'],
            ['name' => 'intracin_ml', 'label' => 'Intracin (ml)', 'type' => 'number', 'placeholder' => 'Masukkan volume Intracin', 'step' => '0.1'],
            ['name' => 'notes', 'label' => 'Catatan', 'type' => 'textarea', 'placeholder' => 'Tambahkan catatan', 'span' => 2],
        ],
        'certificates' => [
            ['name' => 'animal_id', 'label' => 'Kambing', 'type' => 'select', 'placeholder' => 'Pilih Kambing', 'options' => ['BBH-001', 'BBH-014'], 'required' => true],
            ['name' => 'certificate_type_id', 'label' => 'Jenis Sertifikat', 'type' => 'select', 'placeholder' => 'Pilih Jenis Sertifikat', 'options' => ['BIBIT_UNGGUL' => 'Sertifikat Bibit Unggul', 'KELAHIRAN' => 'Akte Kelahiran', 'KEMATIAN' => 'Akte Kematian'], 'required' => true],
            ['name' => 'issue_place', 'label' => 'Tempat Terbit', 'type' => 'text', 'placeholder' => 'Contoh: Ajibarang', 'required' => true],
            ['name' => 'death_date', 'label' => 'Tanggal Kematian', 'type' => 'date', 'show_when' => ['certificate_type_id' => 'KEMATIAN']],
            ['name' => 'death_time', 'label' => 'Waktu Kematian', 'type' => 'time', 'show_when' => ['certificate_type_id' => 'KEMATIAN']],
            ['name' => 'cause_of_death', 'label' => 'Penyebab Kematian', 'type' => 'textarea', 'placeholder' => 'Contoh: Sakit, kecelakaan, atau sebab lainnya', 'span' => 2, 'show_when' => ['certificate_type_id' => 'KEMATIAN']],
        ],
        'rsa-keys' => [
            ['name' => 'key_identifier', 'label' => 'Key Identifier', 'type' => 'text', 'placeholder' => 'Kosongkan untuk dibuat otomatis'],
            ['name' => 'key_length', 'label' => 'Panjang Key', 'type' => 'hidden', 'value' => '2048'],
        ],
    ],
];
